# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:12.9.1

pipelines:
  branches:
    release/staging:
      - step:
          caches:
            - node
          deployment: staging
          script:
            - apt-get update && apt-get install --yes zip
            - zip -r application.zip -r ./* -x *.git* node_modules/\*
            - pipe: atlassian/aws-elasticbeanstalk-deploy:0.6.6
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                APPLICATION_NAME: $APPLICATION_NAME
                ENVIRONMENT_NAME: $ENVIRONMENT_NAME
                ZIP_FILE: 'application.zip'
                S3_BUCKET: $S3_BUCKET
    
    release/development:
      - step:
          caches:
            - node
          deployment: development
          script:
            - apt-get update && apt-get install --yes zip
            - zip -r application.zip -r ./* -x *.git* node_modules/\*
            - pipe: atlassian/aws-elasticbeanstalk-deploy:0.6.6
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                APPLICATION_NAME: $APPLICATION_NAME
                ENVIRONMENT_NAME: $ENVIRONMENT_NAME
                ZIP_FILE: 'application.zip'
                S3_BUCKET: $S3_BUCKET

    release/production:
      - step:
          caches:
            - node
          deployment: production
          script:
            - apt-get update && apt-get install --yes zip
            - zip -r application.zip -r ./* -x *.git* node_modules/\*
            - pipe: atlassian/aws-elasticbeanstalk-deploy:0.6.6
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                APPLICATION_NAME: $APPLICATION_NAME
                ENVIRONMENT_NAME: $ENVIRONMENT_NAME
                ZIP_FILE: 'application.zip'
                S3_BUCKET: $S3_BUCKET
