version: 0.2

phases:
    install:
        commands:
            - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
            - unzip sonar-scanner-cli-4.6.2.2472-linux.zip
            - export PATH=$PATH:./sonar-scanner-4.6.2.2472-linux/bin/
            # - sonar-scanner
            #- pipe: sonarsource/sonarqube-scan:1.0.0
    pre_build:
        commands:
            - echo Logging in to Amazon ECR...
            - AWS_DEFAULT_REGION=us-east-1
            - aws --version
            - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
            - REPOSITORY_URI=704739058071.dkr.ecr.us-east-1.amazonaws.com/mentorhub-youth-mh-crclmsrvr-repo
            - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
            - IMAGE_TAG=${COMMIT_HASH:=stag}
    build:
        commands:
            - echo Build started on `date`
            - echo Building the Docker image...
            - docker build -t $REPOSITORY_URI:stag .
            - docker tag $REPOSITORY_URI:stag $REPOSITORY_URI:$IMAGE_TAG
    post_build:
        commands:
            - echo Build completed on `date`
            - echo Pushing the Docker images...
            - docker push $REPOSITORY_URI:stag
            - docker push $REPOSITORY_URI:$IMAGE_TAG
            - printf '[{"name":"crclmsrvr","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
